# Generated by Django 3.2.9 on 2021-12-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='description',
            field=models.CharField(default='blank', max_length=2048),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='permission',
            field=models.CharField(choices=[('All Rights', 'All Rights'), ('Create and Read', 'Create and Read')], max_length=80),
        ),
    ]
